LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES  := mkbootfs.c
LOCAL_CFLAGS     := -Wall -Wextra -std=gnu11
LOCAL_C_INCLUDES := . $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr/include
LOCAL_ADDITIONAL_DEPENDENCIES := $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr
LOCAL_MODULE     := mkbootfs
include $(BUILD_EXECUTABLE)
